### PR TITLE
Add articles section to media page

### PR DESCRIPTION
**Pull request by alanshaw**
screen shot 2017-08-03 at 12 24 13

...also fixes the watch script in the makefile which wasn't working properly.

### CODE REVIEW

**Comment by diasdavid** [comment]
I know we didn't do any design discussion for this page and I appreciate you kicking it off. It is important to follow the same struct that the IPFS website as, for example:
 
- I like better the format used by https://github.com/libp2p/website/pull/58 where each post ist `<date> [<title>])(<url>)`
- I also like that it is divided by years (signals activity) and that at the top there is space for some selected videos. 

Could you make this happen? Thanks!

**Comment by alanshaw** [comment]
@diasdavid is good now?

screen shot 2017-08-05 at 10 40 21

**Comment by diasdavid** [comment]
I like it more, yes :) quick question, where did you get the list of articles? I would like to try adding more

**Comment by alanshaw** [comment]
They are the articles from the issue (https://github.com/libp2p/website/issues/25). Shall we merge this? We can add more later...

**Comment by diasdavid** [comment]
thank you, @alanshaw :D

**Pull request merged**
