### PR TITLE
chore: add spec links

### PR DESCRIPTION
**Pull request by p-shahi**

### CODE REVIEW

**Comment by p-shahi** [comment]
I started adding spec links here: https://github.com/libp2p/website/pull/173
However, it seems like the site generator doesn’t like it i.e. no hyperlink added to text https://bafybeihwliqh7sfz2cbzuo42duni7nrw3zg3rxodanbrgdxvg5jbjmffqm.on.fleek.co/implementations/

**Comment by dhuseby** [comment]
hrm...I'll dig in and see if I can figure this out

**Comment by dhuseby** [comment]
I see the problem...I'd fix it but I'm not on my dev machine. Check this screenshot out:
Screenshot 2023-05-12 at 11 15 29 PM
You'll see that the .tr.th content is just the string name of the feature. If we look at the partial html file that is used to render this you'll see that it is indeed just putting [the feature name/id and nothing else](https://github.com/libp2p/website/blob/c9d1c90836d32f65e065a7f06ff10b4344e360bb/layouts/partials/implementation.html#L28).

The current code (linked above) is this:
`<th class="head-col">{{ .id }}</th>`

when it needs to be this:
`<th class="head-col"><a href="{{ .url }}" target="_blank">{{ .id }}</a></th>`

**Comment by dhuseby** [comment]
I'll fix it tomorrow if you don't get to it first.

**Comment by dhuseby** [comment]
Probably need to add an if/else/end around this so that we get an anchor when there is a .url defined and we get the current behavior when it isn't.

**Comment by dhuseby** [comment]
yup that worked. @p-shahi I got the link rendering working, we just now need to add the links.

**Comment by BigLep** [comment]
There are more links we can add right per the specs repo?

image

I'm just clueing in that we are missing spec coverage on some areas it looks like.  
In terms of a metric for the project, I'd love to see a percentage of how much is specified out of how much ideally is.

**Comment by dhuseby** [comment]
features that didn't have obvious spec links:
- Transports
  - tcp
  - websocket
  - webrtc-star
- Discovery
  - random-walk (maybe in [kad-dht spec](https://github.com/libp2p/specs/blob/master/kad-dht/README.md)?)
- Peer Routing
  - kbucket
- Publish / Subscribe
  - floodsub
- Storage
  - record

**Pull request merged**
