### PR TITLE
photos slider updates

### PR DESCRIPTION
**Pull request by kolpin**

### CODE REVIEW

**Comment by jesseclay** [comment]
@diasdavid the diffs on this PR are massive due to files being deleted & re-added. Maybe text editor issues?

Any recommendations to make the diff actually reflective of changes?

**Comment by VictorBjelkholm** [comment]
@jesseclay you can add `?w=1` in the end of the URL to only see non-whitespace changes ( like here: https://github.com/libp2p/website/pull/47/files?w=1 ) but changing all tabs to space or vice versa shouldn't happen like this, probably something that comes from the editor that @kolpin is using.

**Comment by jesseclay** [comment]
amazing, thanks @VictorBjelkholm

**Comment by jesseclay** [comment]
looks good @kolpin, thanks.

**Pull request merged**
